### ISSUE TITLE
Clone and install shows some deprecated warnings

### ISSUE THREAD

**Issue by peterennisrda** [fssrepository/fms#4]
![capture1280](https://user-images.githubusercontent.com/1280523/34547744-4fdc1a94-f0f5-11e7-912b-e07de003d506.PNG)

**Comment by raxim1** [comment]
![fms](https://user-images.githubusercontent.com/22751352/34636255-b1e7682a-f29d-11e7-8dd4-60b14a7d610a.png)

For me it was working (ionic serve also), yes, we have problems here, but every time the ionic has got some breaking changes. Leave this at the moment. It's very time consuming also to follow, what the ionic does, i have faced with bugs, the productivity is very low with ionic, with my private project, i simply almost rewritten the ionic ui. (there are some things needs to be done, and i'm improving lots of components at the moment with better functionality set)

It's a problem, but it does not cause me your running issue, in the next bug mentioned.

**Comment by raxim1** [comment]
The last one is related to the tests, but the main thing ionic has many bugs and the mocking library is one of them. The first one is ok, until you don't define your own typings, which you need to try first before it's going to the repo. (many of them won't be accepted and standardized)

**Comment by peterennisrda** [comment]
OK
