### ISSUE TITLE
Build fails to run with ionic serve

### ISSUE THREAD

**Issue by peterennisrda** [fssrepository/fms#5]
![capture1281](https://user-images.githubusercontent.com/1280523/34547757-6a92f1be-f0f5-11e7-9fb8-f94d376237ce.PNG)

```
C:\ae\fms>ionic serve
Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser -
Ctrl+C to cancel
[18:12:17]  watch started ...
[18:12:17]  build dev started ...
[18:12:17]  Proxy added:/api => http://localhost:3000/api
[18:12:17]  clean started ...
[18:12:17]  clean finished in less than 1 ms
[18:12:17]  copy started ...
[18:12:17]  deeplinks started ...
[18:12:17]  deeplinks finished in 149 ms
[18:12:17]  transpile started ...
[18:12:19]  typescript: C:/ae/fms/src/app/main.ts, line: 7
            Cannot find name 'process'.

       L7:  if (process.env.IONIC_ENV === "prod") {
       L8:      enableProdMode();

[18:12:19]  typescript: C:/ae/fms/src/lib/p2p/comparators.ts, line: 16
            Cannot find name 'Buffer'.

      L16:  export class KNodeKeyComparator implements Comparator<Buffer> {
      L17:      canCompare(o: any): boolean {

[18:12:19]  typescript: C:/ae/fms/src/lib/p2p/comparators.ts, line: 18
            Cannot find name 'Buffer'.

      L17:  canCompare(o: any): boolean {
      L18:      return o instanceof Buffer;

[18:12:19]  typescript: C:/ae/fms/src/lib/p2p/comparators.ts, line: 21
            Cannot find name 'Buffer'.

      L21:      compare(o1: Buffer, o2: Buffer, bitIndex: any) {
      L22:          var byteIdx = ~~(bitIndex / 8); //round to integer

[18:12:19]  typescript: C:/ae/fms/src/lib/p2p/comparators.ts, line: 21
            Cannot find name 'Buffer'.

      L21:      compare(o1: Buffer, o2: Buffer, bitIndex: any) {
      L22:          var byteIdx = ~~(bitIndex / 8); //round to integer

[18:12:19]  typescript: C:/ae/fms/src/lib/p2p/k-tree.ts, line: 8
            Cannot find name 'Buffer'.

       L7:  export class KUtil {
       L8:      public static distance(firstId: Buffer, secondId: Buffer) {
       L9:          var distance = 0

[18:12:19]  typescript: C:/ae/fms/src/lib/p2p/k-tree.ts, line: 8
            Cannot find name 'Buffer'.

       L7:  export class KUtil {
       L8:      public static distance(firstId: Buffer, secondId: Buffer) {
       L9:          var distance = 0

[18:12:19]  typescript: C:/ae/fms/src/lib/p2p/web-rtc.ts, line: 6
            Property 'RTCPeerConnection' does not exist on type 'Window'.

       L5:  var wrtc = {
       L6:      RTCPeerConnection: window.RTCPeerConnection || (<any>window).mozRTCPeerConnection ||
       L7:          (<any>window).webkitRTCPeerConnection,

[18:12:19]  typescript: C:/ae/fms/src/lib/p2p/web-rtc.ts, line: 8
            Property 'RTCSessionDescription' does not exist on type 'Window'.

       L7:      (<any>window).webkitRTCPeerConnection,
       L8:  RTCSessionDescription: window.RTCSessionDescription || (<any>window).mozRTCSessionDescription ||
       L9:      (<any>window).webkitRTCSessionDescription,

[18:12:19]  typescript: C:/ae/fms/src/lib/p2p/web-rtc.ts, line: 10
            Property 'RTCIceCandidate' does not exist on type 'Window'.

       L9:      (<any>window).webkitRTCSessionDescription,
      L10:  RTCIceCandidate: window.RTCIceCandidate || (<any>window).mozRTCIceCandidate ||
      L11:      (<any>window).webkitRTCIceCandidate

[18:12:19]  typescript: C:/ae/fms/src/lib/rvt/pbf/decode.worker.ts, line: 68
            Cannot find name 'pako'.

      L67:  } else if (blob.zlibData.length > 0) {
      L68:      data = pako.inflate(blob.zlibData);

[18:12:19]  typescript: C:/ae/fms/src/lib/rvt/rvt/reader.ts, line: 41
            Cannot find namespace 'ProtoBuf'.

      L40:  function sumUp(offsets) {
      L41:      let gOffsets = new Array<ProtoBuf.Long>();
      L42:      offsets.forEach((value, i) => {

[18:12:19]  typescript: C:/ae/fms/src/lib/rvt/rvt/reader.ts, line: 43
            Cannot find name 'ProtoBuf'. Did you mean 'protobuf'?

      L42:  offsets.forEach((value, i) => {
      L43:      let val = ProtoBuf.Long.fromValue(value);
      L44:      if (i === 0) {

[18:12:19]  dev server running: http://localhost:8100/

[OK] Development server running!
     Local: http://localhost:8100
     External: http://192.168.0.89:8100
     DevApp: fms@8100 on EINSTEINIUM

[18:12:19]  copy finished in 2.68 s
[18:12:20]  watch ready in 2.79 s
```

**Comment by peterennisrda** [comment]
```
C:\ae\fms>ionic info

cli packages: (C:\ae\fms\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy


C:\ae\fms>
```

**Comment by peterennisrda** [comment]
I found this reference to the "Cannot find name 'process'." error:

https://github.com/manojdcoder/nativescript-master-technology/commit/676fd4794389ca28e6ef1dd971dbbb984ed5d35a

However, your code  has many different index.d.ts typings files and it
is not clear where this patch could be applied of if it is valid as a solution.

**Comment by peterennisrda** [comment]
I read through the fms design doc. Lots of interesting research, ideas, and possibilities.
This app seems the right place for me to continue looking into the project.
Any timeline on a fix, or should I wait until you have something newer to test?

**Comment by raxim1** [comment]
Eventually it should work (just cloned the repository and run, very likely some global thing is missing), yes the typescript area is not the easiest part, as there is @types/something, and there are some old typings also, and i'm using typescript in webworker also. I would suggest to read through the javascript pbf reader and try to grab the logic and push back to java.

I have very bad experiences with node js and typescript on this front, as i'm using very new stuff which was not up-to-date on typescript level.

The webworker stuff is hard and not that feasible that the user will convert 40GB pbf file on the fly in a browser. It will be converted to my pbf format. Java is far more easier, you haven't file restriction.

Trying to figure out how you can help remotely on this matter. What i realized that you have a little bit newer packages. (node / npm)

**Comment by raxim1** [comment]
You have a little bit newer version of node and npm, but i think we have some basic problem here, as everything is working for me after making a fresh clone and install and serve.

----------------------------------
There are two style of typings, the "process" should come from "@types/node": "^8.0.28".
I have a guess, because it's defined as a dev dependency is causing problem on your side, maybe because i installed as a global also. If you can figure out this problem, there is a big chance to fix your all ones, as the old typings seems to me ok, i haven't seen relevant bugs on that.
-------------------------------------------

The __common folder contains some script for the old style of typings. (which are the proto file - proto is the definition of the pbf format - when you change something on proto, you need to generate it again)

**Comment by raxim1** [comment]
cli packages: (/home/raxim/ae/fms/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.3
    npm               : 5.5.1 
    OS                : Linux 4.10

Misc:

    backend : legacy

**Comment by peterennisrda** [comment]
update to 8.5.7 did not  fix the issue

**Comment by peterennisrda** [comment]
Ionic runs with Angular so the following may be helpful:

https://stackoverflow.com/questions/48336253/cannot-find-name-process-angular-5

`process` is a variable that gives you access to your server.

In no case you are supposed to use it in your Angular application : it's made to be used on your Node server.

If you do that, this means that anyone who is running your application can see your environment variables. That includes, for instance, your API keys.

**Comment by fssrepository** [comment]
Thanks for your reply, the main point is, i don't want to figure out everything when i use very buggy ionic framework. - The FMS was a very initial ionic based project of mine, but i have learnt from the past.

If i will have time, i will move the project away from ionic, and make it better. (At the moment also the FMS project stalled a little bit, as the converter will be written in java, and just only the presentation layer will be html, or native app like - in the last days i dare to code in swift or android java - i also dag into mqtt area)

I have a main project where i deprecated the whole ionic stuff, and moved to angular-cli, which has default support on environment variables. Buffer and so on is definitely needs types to be installed, even if you have some answer, for building purpose the types are missing.

Api keys is exposed either way, most of them is using JWT on android. You can just look at how to use google javascript map api. (acync defer url) It's always changing, and the string of the api key is not encoded.

For temporary reason, if you would like to build, you need to install some typings. (I admit that it's not the best way to solve this problem)

**Comment by fssrepository** [comment]
![image](https://user-images.githubusercontent.com/33239584/37931648-a707680a-3146-11e8-9bd6-d56e160d2b3f.png)

Unfortunately it's not the project fault, you need to install some types attached on the image.

I admit that the process might not be the right way (the project is mostly an initial sample code for the design to start with - although the converter part will be in java)

To use process does not make app riskier, as the api keys are exposed either way, as it's not encoded.= You can easily steal others' google map javascript api key for example. It's designed to be exposed, as it's kept changing.
